name: semantic-helper-tag
description: 'Ensure a tag does not exit and create/move the tags'
inputs:
  mode:
    description: 'whether to test for the tag existence or set it, one of "test" or "set"'
    required: true
  tag:
    description: 'the tag to set'
    required: true
runs:
  using: "composite"
  steps:
    - run: ./action.sh ${{ inputs.mode }} ${{ inputs.tag }}
      shell: bash
